services:
  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    ports:
      - 65432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./createDB.sql:/docker-entrypoint-initdb.d/createDB.sql:ro