"""Add review_issue author

Revision ID: 2005d5d7b4c6
Revises: de6b4fd00d00
Create Date: 2024-12-22 23:45:26.664906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2005d5d7b4c6'
down_revision = 'de6b4fd00d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_author', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_issue', schema=None) as batch_op:
        batch_op.drop_column('review_author')

    # ### end Alembic commands ###
