"""Add write_issue_response_prompt column to user_prompts

Revision ID: 554928d13b42
Revises: 2005d5d7b4c6
Create Date: 2024-12-30 14:12:04.520787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554928d13b42'
down_revision = '2005d5d7b4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('write_issue_response_prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_prompts', schema=None) as batch_op:
        batch_op.drop_column('write_issue_response_prompt')

    # ### end Alembic commands ###
