"""Add review_issue review id

Revision ID: de6b4fd00d00
Revises: b0e76b1be9e1
Create Date: 2024-12-22 22:40:00.404162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6b4fd00d00'
down_revision = 'b0e76b1be9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_issue', schema=None) as batch_op:
        batch_op.drop_column('review_id')

    # ### end Alembic commands ###
